"""Generate docs/data_provenance.md from the download manifest plus each adapter's PROVENANCE metadata.

The document is never hand-edited (BUILD_PLAN §4). `lotline provenance --write` regenerates it; `--check`
fails if it is out of date or if any processed table was built from a source the document doesn't cover.

Per source, the manifest supplies what was actually downloaded (URLs, vintages, access dates, bytes, sha256,
license as recorded at download time); the adapter supplies the human parts (title, cleaning steps, known
limitations, attribution).
"""

from __future__ import annotations

from collections import defaultdict
from email.utils import parsedate_to_datetime
from pathlib import Path

from lotline.adapters.national import acs, bps, bps_state, decennial, fhfa, fred
from lotline.io.store import DataStore, ManifestEntry

REPO_ROOT = Path(__file__).resolve().parents[2]
DOC_PATH = REPO_ROOT / "docs" / "data_provenance.md"

# manifest source id -> adapter module exposing PROVENANCE
ADAPTERS = {
    bps.SOURCE: bps,
    bps_state.SOURCE: bps_state,
    fhfa.SOURCE: fhfa,
    acs.SOURCE: acs,
    fred.SOURCE: fred,
    decennial.SOURCE: decennial,
}

HEADER = """# Lotline: Data Provenance

<!-- GENERATED by `lotline provenance --write` from the download manifest and adapter metadata.
     Do not edit by hand: change the adapter's PROVENANCE block and regenerate. -->

Every dataset Lotline uses: where it came from, which version, when it was accessed, under what license,
how it was cleaned, and its known limitations (Participant Handbook, Data and Resources). Data is downloaded
by `lotline fetch` into `LOTLINE_DATA_DIR`, never committed; each download is logged with its sha256 in
`manifest.jsonl` there, so a pull can be verified byte for byte.
"""


class ProvenanceError(RuntimeError):
    pass


def _vintages(entries: list[ManifestEntry]) -> str:
    """Vintage labels from raw/<source>/<vintage>/... paths, compressed to a range when they are years."""
    labels = sorted({Path(e.path).parts[2] for e in entries if len(Path(e.path).parts) > 3})
    if labels and all(v.isdigit() for v in labels) and len(labels) > 2:
        return f"{labels[0]}–{labels[-1]} ({len(labels)} vintages)"
    return ", ".join(labels) or "n/a"


def _dates(entries: list[ManifestEntry]) -> str:
    days = sorted({e.accessed_at[:10] for e in entries})
    return days[0] if len(days) == 1 else f"{days[0]} to {days[-1]}"


def _publisher_dates(entries: list[ManifestEntry]) -> str:
    stamps = [parsedate_to_datetime(e.last_modified) for e in entries if e.last_modified]
    return f"; publisher files last modified up to {max(stamps):%Y-%m-%d}" if stamps else ""


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render(manifest: list[ManifestEntry]) -> str:
    """Build the markdown document. Only the latest manifest entry per URL counts."""
    latest: dict[str, ManifestEntry] = {}
    for e in manifest:
        latest[e.url] = e
    by_source: dict[str, list[ManifestEntry]] = defaultdict(list)
    for e in latest.values():
        by_source[e.source].append(e)

    unknown = sorted(set(by_source) - set(ADAPTERS))
    if unknown:
        raise ProvenanceError(f"manifest has sources with no adapter metadata: {unknown}")

    rows, details = [], []
    for source in sorted(by_source, key=lambda s: ADAPTERS[s].PROVENANCE["title"]):
        entries = sorted(by_source[source], key=lambda e: e.path)
        meta = ADAPTERS[source].PROVENANCE
        licenses = sorted({e.license for e in entries})
        version = _vintages(entries) + _publisher_dates(entries)
        rows.append(
            "| "
            + " | ".join(
                _cell(x)
                for x in (
                    f"{meta['title']} (`{source}`)",
                    meta["landing_url"],
                    version,
                    _dates(entries),
                    "; ".join(licenses),
                    "; ".join(meta["cleaning"]),
                    "; ".join(meta["limitations"]),
                )
            )
            + " |"
        )
        size = sum(e.bytes for e in entries)
        detail = [
            f"### {meta['title']}",
            "",
            f"- **Source id:** `{source}` → table `{meta['table']}` (adapter `{entries[-1].adapter}` "
            f"v{entries[-1].adapter_version})",
            f"- **Source:** {meta['landing_url']}",
            f"- **Version:** {version}",
            f"- **Accessed:** {_dates(entries)}",
            f"- **Files:** {len(entries)} ({size / 1e6:,.1f} MB); URLs and sha256 in `manifest.jsonl`",
            f"- **License / terms:** {'; '.join(licenses)}",
        ]
        if meta.get("attribution"):
            detail.append(f"- **Required attribution:** {meta['attribution']}")
        detail += ["", "**Cleaning steps**", ""] + [f"1. {s}" for s in meta["cleaning"]]
        detail += ["", "**Known limitations**", ""] + [f"- {s}" for s in meta["limitations"]]
        details.append("\n".join(detail))

    table = [
        "| Dataset | Source (URL) | Version | Access date | License / terms | Cleaning steps "
        "| Known limitations |",
        "|---|---|---|---|---|---|---|",
        *rows,
    ]
    return "\n".join([HEADER, "## Summary", "", *table, "", "## Datasets", "", "\n\n".join(details), ""])


def processed_sources(store: DataStore) -> set[str]:
    """Manifest source ids behind every processed table file (processed/<st>/<table>/<source>.parquet)."""
    from lotline.adapters.national import SOURCES

    by_cli_name = {name: module for name, (module, _) in SOURCES.items()}
    found = set()
    for path in (store.root / "processed").glob("*/*/*.parquet"):
        module = by_cli_name.get(path.stem)
        if module is None:
            raise ProvenanceError(f"{path}: no registered source named {path.stem!r}")
        found |= set(getattr(module, "MANIFEST_SOURCES", [getattr(module, "SOURCE", path.stem)]))
    return found


def write(store: DataStore, doc: Path = DOC_PATH) -> Path:
    doc.write_text(render(store.manifest()))
    return doc


def check(store: DataStore, doc: Path = DOC_PATH) -> list[str]:
    """Problems that make the committed document stale or incomplete (empty list = OK)."""
    problems = []
    manifest = store.manifest()
    documented = {e.source for e in manifest}
    missing = sorted(processed_sources(store) - documented)
    if missing:
        problems.append(f"processed tables built from sources with no manifest entries: {missing}")
    if not doc.exists() or doc.read_text() != render(manifest):
        problems.append(f"{doc.name} is out of date: run `lotline provenance --write`")
    return problems
